gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet


# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title: Ian Glen Neal
email: ian.gl.neal@gmail.com
tagline: ''
description: >-
  Future PhD candidate Computer Science, with a focus in Systems and Computer
  Architecture.
url: 'about.iangneal.io'
baseurl: '/'

author:
  name: 'Ian Glen Neal'
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
version:          2.1.0
#
#github:
#  repo:           https://github.com/poole/hyde
