gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet


# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Ian Glen Neal
email: ian.gl.neal@gmail.com
tagline: ''
description: >-
  Future PhD candidate Computer Science, with a focus in Systems and Computer
  Architecture.
url: 'about.iangneal.io'
baseurl: '/'

# Social media accounts
twitter_username: iangneal
github_username: dahca
linkedin_username: ianglenneal
google_plus_username:
facebook_username:
dribbble_username:

# Various emails
gmail_address: ian.gl.neal@gmail.com
utexas_address: ian.glen.neal@utexas.edu


# Atom.xml -- RSS feed
author:
  name: 'Ian Glen Neal'

# Paginate: break up block post list
paginate: 5

# Custom vars
version:

github:
  repo:
