plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-gist
  - redcarpet


# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Ian Glen Neal
email: ian.gl.neal@gmail.com
tagline: ''
description: >-
  PhD Pre-Candidate in Computer Science with a focus in Systems and
  Computer Architecture.
url: 'about.iangneal.io'
baseurl: /

# Social media accounts
twitter_username: iangneal
medium_username: iangneal
github_username: Dahca
linkedin_username: ianglenneal
stackoverflow_username: 7869944
google_plus_username:
facebook_username:
dribbble_username:

# Various emails
gmail_address: ian.gl.neal@gmail.com
school_address: iangneal@umich.edu


# Atom.xml -- RSS feed
author:
  name: 'Ian Glen Neal'

# Paginate: break up block post list
paginate: 5
paginate_path: "/blog/page:num/"

# Custom vars
version:

github:
  repo:
